### ISSUE TITLE
Tab completion changes directory

### ISSUE THREAD

**Issue by jeffkole** [mbland/go-script-bash#123]
If you use tab completion, your current directory is changed to the rootdir for the go script.

For example:

```
cd /tmp
git clone git@github.com:mbland/go-script-bash.git
cd go-script-bash
eval "$(./go env -)"
cd /tmp
go he<tab>
pwd
```

The result is that the current working directory is `/tmp/go-script-bash`.

I would expect that running the `go` script would not change my current working directory.

There are tests for the directory being changed when completion is in use, so I imagine there is a good reason for it.  Will you please explain?

**Comment by mbland** [comment]
It's because filename completion relative to `_GO_ROOTDIR` won't work without it. But now that I think about it, there may be a way to convert the generated paths from relative to absolute when `"$PWD" != "$_GO_ROOTDIR"`. It may junk up the command line, but perhaps it may be less surprising/annoying. What do you think?

**Comment by jeffkole** [comment]
I'd vote for the least surprising and annoying behavior :)  To me, using tab completion should have no side effects.

**Comment by mbland** [comment]
So interpreting that as expanding to absolute paths is less surprising and annoying, I'll look into implementing that, then.

**Comment by jeffkole** [comment]
Would it be possible, and a reasonable solution, to change into the `_GO_ROOTDIR` for the completion and then back once the completion is complete?

**Comment by mbland** [comment]
Yeah, that's what I was thinking. Gonna give it a try now. Learned a lot about Bash since writing that bit of code last summer, so maybe I'll have better luck.

**Comment by mbland** [comment]
Good news; got a working workaround. Just gonna polish and test, then I'll send a PR and add you to it.

**Comment by mbland** [comment]
True to form, after getting the quick solution done, I spent all day thinking through how to do it right. #124 is now in-flight.

The bonus good news is, it didn't require doing a `cd` dance at all, or expanding absolute paths. I'll be interested to hear your feedback on the new experience once it's merged (which I anticipate will be about fifteen minutes from now).

**Comment by jeffkole** [comment]
Looks great.  Thank you for the quick turnaround and solid solution.
