### ISSUE TITLE
Better error checking in module loading

### ISSUE THREAD

**Issue by JohnOmernik** [mbland/go-script-bash#25]
When modules paths are checked in go-script-bash/lib/internal/use basically the script tries to source them and if it fails, it just ends up on unknown module

  if ! . "$_GO_CORE_DIR/lib/$__go_module_name" 2>/dev/null &&
     ! . "$_GO_SCRIPTS_DIR/plugins/${__go_module_name/\///lib/}" 2>/dev/null &&
     ! . "$_GO_SCRIPTS_DIR/lib/$__go_module_name" 2>/dev/null; then
    @go.printf "ERROR: Unknown module: $__go_module_name" >&2
    exit 1
  fi

However, this doesn't differentiate between the module not existing, and the module having an error. I.e. if the module file exists, but has a bash syntax error, it will fail with the same "Unknown module" error that it fails with if the module file doesn't exist. 

Ideally, we'd have two messages, one for issue with the module file not existing, another stating the file doesn't exist, however there was an error in loading it.

**Comment by mbland** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [v1.3.0](https://trello.com/c/qS0zfBCI/2-v1-3-0)
