### ISSUE TITLE
Optional `strftime`-style timestamps in `log` module

### ISSUE THREAD

**Issue by mbland** [mbland/go-script-bash#34]
Per @JohnOmernik, there should be the option to precede log messages with `strftime`-style timestamps.

Starting with some 4.x version of Bash, the `%(datefmt)T` format specifier provides exactly this behavior; Bash 3.2, as ships with macOS, does not. So there'd need to be logic to use the builtin format if available, resort to the `date` program if not, and produce a warning if neither happens to be available.

**Comment by mbland** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [v1.3.0](https://trello.com/c/qS0zfBCI/2-v1-3-0)

**Comment by JohnOmernik** [comment]
So, I while it may be clunky and inellagant to put a $(date 'format')  for logging, I would say until we have platform uniformity, it's just best to have one approach.... unless there are some serious performance concerns. Perhaps instead of detecting platform, we set through a conf value in go.conf "USE_STRFTIME"?

**Comment by mbland** [comment]
What I was thinking was that there'd be an optional `_GO_TIMESTAMP_FORMAT` or some such, and timestamp output would be triggered off of whether it was set or not. And then, there'd be a lightweight one-time check to see which format to use. Something like:

```bash
@go.timestamp() {
  if [[ -z "$__GO_TIMESTAMP_IMPL" ]]; then
    if [[ -z "$_GO_TIMESTAMP_FORMAT" ]]; then
      export __GO_TIMESTAMP_IMPL='none'
    elif printf "%('%Y')T" &>/dev/null; then
      export __GO_TIMESTAMP_IMPL='printf'
    elif command -v 'date' >/dev/null; then
      export __GO_TIMESTAMP_IMPL='date'
    else
      export __GO_TIMESTAMP_IMPL='none'
      @go.log WARN "Builtin timestamps not supported and date command not found."
    fi
  fi

  case "$__GO_TIMESTAMP_IMPL" in
  printf)
    printf "%($_GO_TIMESTAMP_FORMAT)T"
  date)
    date "+$_GO_TIMESTAMP_FORMAT"
  esac
}
```

Not having either the `printf` or `date` implementations available would be an extreme case, but I like to handle those, too. :-)
