### ISSUE TITLE
Way to configure behaivior of @go.log FATAL

### ISSUE THREAD

**Issue by JohnOmernik** [mbland/go-script-bash#95]
I am liking the new changes.  One thing I noticed was now when I use @go.log FATAL it produces my error message as well as a stack trace. 

From a user point of view, if I am trapping an error (thus producing the @go.log FATAL) what  I provide to them should be sufficient... perhaps there are other cases where I wish to provide them a stack trace, but I've found most of the place I've used @go.log FATAL my message is sufficient. 

For example: 

If I run a script and the script expects a certain argument -c=/path/to/conf

I try to get the conf file, and if it doesn't exist

if [ ! -f "CONF_FILE" ]; then
    @go.log FATAL "Please provide a valid path to configuration file with -c="
fi

The stack trace is not needed here, and if anything confuses the user. (Think "Java Errors") 

Thus, I am guessing you have a way to enable or disable stack traces globally, however, maybe we should have two "FATAL"s, one for trapped errors like mine, and another when we need more debugging?

DEBUGFATAL? (lots of characters?) DBFTL? DBFATAL? FEMFATAL? (Ok that last one is pushing it). 

Am I making sense or rambling?

**Comment by mbland** [comment]
Hey @JohnOmernik! It totally makes sense; you're not rambling. I'd wondered whether to make the trace optional. I'm thinking a global default variable that can be overridden by an invocation if needed, as other applications may want the trace and only disable it on occasion. How about `_GO_LOG_FATAL_SHOW_STACK`?

**Comment by JohnOmernik** [comment]
One of the reasons I like having two different FATAL options (one with stack and one without) is that it is easy for the developer to change as needed without changing a global variable... I guess I am worried about code clutter.

**Comment by mbland** [comment]
That makes sense. How about `FAIL` or `QUIT`?

And by the same token, `@go.critical_section_begin` can take an optional argument that can override the log level on error to `FAIL` or `QUIT`.

**Comment by JohnOmernik** [comment]
So FAIL would produce a stack trace, and QUIT would not? That makes sense.  I will require a bunch of changes in my code, but I can live with that :)

**Comment by mbland** [comment]
I was thinking of keeping `FATAL` as-is to produce a stack trace, and `QUIT` (or `FAIL`) to exit without one. But the idea of switching `FATAL` to `FAIL` is interesting, too.

**Comment by mbland** [comment]
Hey John, hope to implement `@go.log QUIT` by tomorrow. Currently almost finished slaying my current white whale (#49).
